import { MultiDirectedGraph } from "graphology";
import { describe, expect, it } from "vitest";

import { computeNodeImportance } from "./pagerank.js";

// Pre-swap baseline captured before slice 020's graphology-pagerank →
// graphology-metrics library swap. Generated by running PageRank with
// { alpha: 0.85, tolerance: 1e-6, maxIterations: 100 } against the same
// fixture graphs. Post-swap scores MUST match these within 1e-9 per node
// (spec slice 020 SC-005).
const PRE_SWAP_BASELINE = {
  starGraph: {
    center: 0.5121961157031062,
    "leaf-0": 0.0975607768593787,
    "leaf-1": 0.0975607768593787,
    "leaf-2": 0.0975607768593787,
    "leaf-3": 0.0975607768593787,
    "leaf-4": 0.0975607768593787,
  },
  disconnectedGraph: {
    a: 0.17543839772251535,
    b: 0.32456160227748465,
    c: 0.17543839772251535,
    d: 0.32456160227748465,
  },
} as const;

function starGraph(): MultiDirectedGraph {
  const graph = new MultiDirectedGraph();
  graph.addNode("center");
  for (let i = 0; i < 5; i += 1) {
    const id = `leaf-${i}`;
    graph.addNode(id);
    graph.addEdgeWithKey(`e-${i}`, id, "center");
  }
  return graph;
}

describe("computeNodeImportance", () => {
  it("scores the center of a star graph higher than the leaves", () => {
    const graph = starGraph();

    const scores = computeNodeImportance(graph);

    const centerScore = scores.get("center") ?? 0;
    const leafScore = scores.get("leaf-0") ?? 0;
    expect(centerScore).toBeGreaterThan(leafScore);
  });

  it("returns an empty map for an empty graph", () => {
    const graph = new MultiDirectedGraph();

    const scores = computeNodeImportance(graph);

    expect(scores.size).toBe(0);
  });

  it("returns a single entry of value 1 for a single-node graph", () => {
    const graph = new MultiDirectedGraph();
    graph.addNode("solo");

    const scores = computeNodeImportance(graph);

    expect(scores.size).toBe(1);
    expect(scores.get("solo")).toBe(1);
  });

  it("does not throw on disconnected components and produces a finite score for every node", () => {
    const graph = new MultiDirectedGraph();
    graph.addNode("a");
    graph.addNode("b");
    graph.addNode("c");
    graph.addNode("d");
    graph.addEdgeWithKey("e1", "a", "b");
    graph.addEdgeWithKey("e2", "c", "d");

    const scores = computeNodeImportance(graph);

    for (const id of ["a", "b", "c", "d"]) {
      const score = scores.get(id);
      expect(score).toBeDefined();
      expect(Number.isFinite(score)).toBe(true);
    }
  });

  it("matches the pre-swap baseline within 1e-9 on the star graph (slice 020 SC-005)", () => {
    const scores = computeNodeImportance(starGraph());

    for (const [node, expected] of Object.entries(PRE_SWAP_BASELINE.starGraph)) {
      const actual = scores.get(node);
      expect(actual).toBeDefined();
      // toBeCloseTo's numDigits=9 → tolerance of 0.5e-9, satisfying SC-005.
      expect(actual).toBeCloseTo(expected, 9);
    }
  });

  it("matches the pre-swap baseline within 1e-9 on the disconnected graph (slice 020 SC-005)", () => {
    const graph = new MultiDirectedGraph();
    ["a", "b", "c", "d"].forEach((n) => graph.addNode(n));
    graph.addEdgeWithKey("e1", "a", "b");
    graph.addEdgeWithKey("e2", "c", "d");

    const scores = computeNodeImportance(graph);

    for (const [node, expected] of Object.entries(PRE_SWAP_BASELINE.disconnectedGraph)) {
      const actual = scores.get(node);
      expect(actual).toBeDefined();
      expect(actual).toBeCloseTo(expected, 9);
    }
  });
});
