name: build

on:
  workflow_call:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5 # v2
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Setup workspace
        uses: ./.github/actions/setup
      - name: Turbo build
        run: pnpm build
      - name: Upload build artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: dextree-build-dist
          path: packages/*/dist
          if-no-files-found: error
          retention-days: 1
          include-hidden-files: false
