name: spell-check

on:
  workflow_call:

jobs:
  spell-check:
    name: spell-check
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5 # v2
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: typos
        uses: crate-ci/typos@5374cbf686e897b15713110e233094e2874de7ef # master
        with:
          files: ./
