name: typecheck

on:
  workflow_call:

permissions:
  contents: read

jobs:
  typecheck:
    name: typecheck
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5 # v2
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Setup workspace
        uses: ./.github/actions/setup
      - name: TypeScript
        run: pnpm typecheck
