name: Lock threads

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  lock:
    name: lock
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5 # v2
        with:
          egress-policy: audit
      - name: Lock resolved threads
        uses: dessant/lock-threads@7266a7ce5c1df01b1c6db85bf8cd86c737dadbe7 # v6.0.0
        with:
          issue-inactive-days: 14
          pr-inactive-days: 14
          add-issue-labels: locked
          add-pr-labels: locked
          process-only: "issues, prs"
