name: Lock threads

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  lock:
    name: lock
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5 # v2
        with:
          egress-policy: audit
      - name: Lock resolved threads
        uses: dessant/lock-threads@1bf7ec25051fe7c00bdd17e6a7cf3d7bfb7dc771 # v5
        with:
          issue-inactive-days: 14
          pr-inactive-days: 14
          add-issue-labels: locked
          add-pr-labels: locked
          process-only: "issues, prs"
